apiVersion: v1
kind: Service
metadata:
  name: svc-hama
  namespace: hama-web
spec:
  type: LoadBalancer
  selector:
    app: hama
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hama-dep
  namespace: hama-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hama
  template:
    metadata:
      name: hama-pod
      labels:
        app: hama
    spec:
      containers:
      - name: hama-con
        image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/hama-web:7
